
fireworks.min.js: src/utils.js src/traits.js src/moods.js src/fireworks.js 
	cat src/utils.js src/traits.js src/moods.js src/fireworks.js \
        | jsmin "'I feel' - a digital artwork commissioned by The Resilience Space" \
                "(C) Copyright Jonathan Hogg, 2012, www.jonathanhogg.com" "All rights reserved." > fireworks.min.js

